language: perl
matrix:
    fast_finish: true
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -n --installdeps ."
    - "cpanm -n Date::Utility" 
    - "cpanm -n Format::Util::Numbers"
    - "cpanm -n Try::Tiny"
    - "cpanm -n Math::Trig"
    - "cpanm -n List::Util"
    - "cpanm -n List::MoreUtils"
    - "cpanm -n Test::Perl::Critic" 
script:
  perl Makefile.PL && make test
